
NumPy was introduced in 2006 to address the inefficiencies of Python in dealing with large amounts of data.
- Written in C and FORTRAN.
- Internal data structure uses C arrays.
- Python API for seamless integration with Python.
- Provides its own array types (ND-arrays).
- Arrays retain most Python collection behaviours, so that it looks and feels ‘native’ to Python language.
- Incorporates fast maths libraries, such as OpenBLAS (default, open source), for efficient linear algebraic operations (dot products, matrix multiply, etc.).

Note: To use NumPy it is necessary to import it.
```python
import numpy as np
```


In [5]:
import numpy as np

### ND-arrays
## ND-arrays stands for N-dimensional arrays.
- The basic data type in NumPy, intended to replace Python’s list.
- Can be created from Python’s list using numpy.array().
- nd-arrays are mutable.
- numpy.arange() produces a sequence of numbers contained in an array.

In [6]:
payment= np.array([6.99,12.4,75.00,1.55])

## Creating a 1-dimentional array:
```
import numpy as np
arr=np.array([1,3,5,7,9])
print(arr)
```

In [7]:
import numpy as np
arr=np.array([1,3,5,7,9])
print(arr)

[1 3 5 7 9]


## Creating a 2-dimentional array:
```
import numpy as np
arr=np.array([[1,3,5,7,9], [2,4,6,8]])
print(arr2)
```

In [1]:
import numpy as np
arr2=np.array([[1,3,5,7], [2,4,6,8]])
print(arr2)

[[1 3 5 7]
 [2 4 6 8]]


The ndim attribute returns the number of dimensions of the array:

In [20]:
arr2.ndim

2

### arange() creates an array with evenly spaced values.
- start: The first value in the array.
- stop: The number that defines the end of the array. It is not included in the array.
- step: The spacing (difference) between each two consecutive values in the array. The default step is 1. Step cannot be zero.
- dtype: The type of the elements of the output array. Defaults to None. If dtype is omitted, arange() will try to deduce the type of the array elements from the types of start, stop, and step.

In [9]:
MyArray = np.arange(start=1, stop=10, step=2)
print(MyArray)

[1 3 5 7 9]


In [27]:
MyArray = np.arange(start=1, stop=10, step=3)
print(MyArray)

[1 4 7]


## All arrays can only contain elements of the same data type.
- This is valid for ND-arrays too.
- The type of the element in an array is recorded as a dtype object:
- Standard Python data types can be used as dtypes: e.g., int, float, str.
- dtype of an array can be obtained using array.dtype property.
- We can perform type conversion using array.astype(new_type).
- The new_type must be compatible with the original type of the elements.
- If in doubt, NumPy automatically converts an array to an array of strings.

In [29]:
import numpy as np

# Create a numpy array
original_array = np.array([1, 2, 3, 4, 5])

# Define the new type
new_type = np.float64

# Create a new array with the new type
new_array = original_array.astype(new_type)

# Print the original and new arrays
print("Original array:", original_array)
print("New array with new type:", new_array)


Original array: [1 2 3 4 5]
New array with new type: [1. 2. 3. 4. 5.]


## The built-in function len() does not work with nd-arrays.
- To find out the size of a nd-array, use array.size property.
- To find out the shape (size of each dimension) of an array, use array.shape property.
- To change the shape of an array, use array.reshape().
### Note: It is the programmer’s responsibility to make sure the new shape is compatible with the total number of elements.

The shape attribute returns a tuple with the number of elements in each dimension.

In [11]:
import numpy as np

# Define the original numpy array
arr2 = np.array([[1, 3, 5, 7, 9, 11], [2, 4, 6, 8, 10, 12]])

# Print the shape of the original array
print("Original array shape:", arr2.shape)
print(arr2)
# Reshape the array to a 3x4 array
arr3x4 = arr2.reshape(3, 4)

# Print the shape of the new array
print("New array shape:", arr3x4.shape)
print(arr3x4)


Original array shape: (2, 6)
[[ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]
New array shape: (3, 4)
[[ 1  3  5  7]
 [ 9 11  2  4]
 [ 6  8 10 12]]


# Broadcasting operations
Broadcasting in NumPy allows operations to be performed on arrays of different shapes, such as scalar values or arrays with different dimensions. 


## Here's an example demonstrating broadcasting operations on the given arrays:

In [13]:
import numpy as np

# Define the payments array
payments = np.array([6.99, 12.40, 75.00, 1.55])

# Define the transaction fee
transaction_fee = 1.00

# Subtract transaction_fee from payments using broadcasting
payments_after_fee = payments - transaction_fee

# Define the VAT (Value Added Tax) rate
vat = 1.20

# Multiply payments by VAT using broadcasting
payments_with_vat = payments * vat

# Print the results
print("Payments after subtracting transaction fee:", payments_after_fee)
print("Payments with VAT applied:", payments_with_vat)


Payments after subtracting transaction fee: [ 5.99 11.4  74.    0.55]
Payments with VAT applied: [ 8.388 14.88  90.     1.86 ]


## Broadcasting: Elementwise operators: ~ (NOT) & (AND) | (OR) ^ (XOR)

### Example: <, > &
You can use comparison operators (>, <) and the logical AND operator (&) to filter values in the payments array that are greater than 5.00 and less than 50.00:

In [60]:
import numpy as np

# Define the payments array
payments = np.array([6.99, 12.40, 75.00, 1.55])
x=payments>5.0
print(x)
print(payments > 5.00)
print(payments < 50.00)

[ True  True  True False]
[ True  True  True False]
[ True  True False  True]


# Slicing and Dicing
## Standard Python list slices:
- array[i] obtains the i-th element.
- array[n:m] obtains the elements array[n], array[n+1], …, array[m-1] in a new array.
- array[I,j] obtains the element on row I and column j of a 2-dimensional array.
## New to ND-arrays:
### Cherry-picking
- array[[2, 4, 5, 1]] obtains the elements array[2], array[4], array[5], array[1] in a new array.
- Cherry picking list can be any Python iterator with integer elements.
### Filtering
```array[[True, True, False, … False, True]]``` obtains the elements from positions marked as True in a new array and omits those marked by False.
- Filter list can be any Python iterator with Boolean elements, and its length must be the same as the array.
- The filter list is usually computed rather than written by hand.

In [3]:
import numpy as np

# Define the payments array
payments = np.array([6.99, 12.40, 75.00, 1.55])

print("1. ", payments[0:2])

print("2. ", payments[2:])

print("3. ", payments[[0,2]])

gt5=payments[(payments > 5.0)]
print("4. ", gt5)
lt50=payments[(payments < 50.0)]
print("5. ", lt50)
# Filter payments greater than 5.00 and less than 50.00 using logical AND operator
filtered_payments = payments[(payments > 5.00) & (payments < 50.00)]

# Print the filtered payments
print("6. Filtered payments between 5.00 and 50.00:", filtered_payments)
print("7. ", payments[(payments < 50.00)])


1.  [ 6.99 12.4 ]
2.  [75.    1.55]
3.  [ 6.99 75.  ]
4.  [ 6.99 12.4  75.  ]
5.  [ 6.99 12.4   1.55]
6. Filtered payments between 5.00 and 50.00: [ 6.99 12.4 ]
7.  [ 6.99 12.4   1.55]


# Mathematical & Statistical Methods
## Functions acting on an entire array
- numpy.all
- numpy.any

In [98]:
import numpy as np

# Define the payments array
payments = np.array([6.99, 12.40, 75.00, 1.55])
np.all(payments > 1)
print("1. ", np.all(payments > 1))
np.any(payments<2)
print("2. ", np.any(payments<2))

1.  True
2.  True


In [100]:
import numpy as np

# Example numpy array
payments = np.array([6.99, 12.40, 75.00, 1.55])

# Statistical functions
sum_result = np.sum(payments)
min_result = np.min(payments)
max_result = np.max(payments)
mean_result = np.mean(payments)
median_result = np.median(payments)
var_result = np.var(payments)
std_result = np.std(payments)
corrcoef_result = np.corrcoef(payments)

# Printing the results
print("Array:")
print(payments)
print("\nSum:", sum_result)
print("Minimum:", min_result)
print("Maximum:", max_result)
print("Mean:", mean_result)
print("Median:", median_result)
print("Variance:", var_result)
print("Standard Deviation:", std_result)
print("Correlation Coefficients:")
print(corrcoef_result)



Array:
[ 6.99 12.4  75.    1.55]

Sum: 95.94
Minimum: 1.55
Maximum: 75.0
Mean: 23.985
Median: 9.695
Variance: 882.225425
Standard Deviation: 29.702279794655492
Correlation Coefficients:
1.0


# Ufuncs
### Universal functions
- A universal function, or ufunc, is a function that performs element-wise operations on data in ndarrays.
- they are fast!


In [103]:
import numpy as np

# Example numpy array
payments = np.array([6.99, 12.40, 75.00, 1.55])

# numpy.sqrt(): Compute the square root of each element in the array
sqrt_result = np.sqrt(payments)

# numpy.square(): Compute the square of each element in the array
square_result = np.square(payments)

# numpy.exp(): Compute the exponential of each element in the array (e^x)
exp_result = np.exp(payments)

# numpy.log(): Compute the natural logarithm (base e) of each element in the array
log_result = np.log(payments)

# numpy.sign(): Compute the sign of each element in the array (-1 if negative, 0 if zero, 1 if positive)
sign_result = np.sign(payments)

# numpy.isnan(): Check if each element in the array is NaN (Not a Number)
isnan_result = np.isnan(payments)

# numpy.sin(): Compute the sine of each element in the array
sin_result = np.sin(payments)

# numpy.add(): Add two arrays element-wise
add_result = np.add(payments, payments)  # Just demonstrating numpy.add() with itself for simplicity

# Printing the results
print("Array:")
print(payments)
print("\nnumpy.sqrt():", sqrt_result)
print("numpy.square():", square_result)
print("numpy.exp():", exp_result)
print("numpy.log():", log_result)
print("numpy.sign():", sign_result)
print("numpy.isnan():", isnan_result)
print("numpy.sin():", sin_result)
print("numpy.add():", add_result)


Array:
[ 6.99 12.4  75.    1.55]

numpy.sqrt(): [2.64386081 3.52136337 8.66025404 1.24498996]
numpy.square(): [4.88601e+01 1.53760e+02 5.62500e+03 2.40250e+00]
numpy.exp(): [1.08572148e+03 2.42801617e+05 3.73324200e+32 4.71147018e+00]
numpy.log(): [1.94448056 2.51769647 4.31748811 0.43825493]
numpy.sign(): [1. 1. 1. 1.]
numpy.isnan(): [False False False False]
numpy.sin(): [ 0.64941485 -0.16560418 -0.38778164  0.99978376]
numpy.add(): [ 13.98  24.8  150.     3.1 ]


### These universal functions perform element-wise operations on arrays:

- numpy.sqrt(): Computes the square root of each element in the array.
- numpy.square(): Computes the square of each element in the array.
- numpy.exp(): Computes the exponential of each element in the array.
- numpy.log(): Computes the natural logarithm (base e) of each element in the array.
- numpy.sign(): Computes the sign of each element in the array (-1 if negative, 0 if zero, 1 if positive).
- numpy.isnan(): Checks if each element in the array is NaN (Not a Number).
- numpy.sin(): Computes the sine of each element in the array.
- numpy.add(): Adds two arrays element-wise.